# Configuration file for TravisCI
os: linux
dist: xenial
language: python
python: "3.6"
notifications:
  email: false

# Only build pushes from the master branch. PRs are always built.
branches:
  only:
    - master

env:
  global:
    # Doctr deploy key for ige-geophysics/ige-geophysics.github.io
    - secure: "cgUFTNHf9O/St+3j0VZLkb2OAnC9EjAEekTCAEbbo2wdFcfKElQki0ciRPzC7zHVOkcRywXY1kuDEi75Ms2JafzMhgppfQE66dApo+PNl2AoLZKxx+QREPNUzbUn2W41qJGLvBAsNuaQNT/eOTcp1PgQO9JEdPdkrlyqpAvrG0H1SUsiRNuHyE87I4D8twmi+Jw4XBnLr/7aX/NNsGosJlOU+pz3foGQ/Nj7WRlstr1fIjDVL8DA7Q0WDb4WIF3BUedStdFK/W83j9obL1dJsFrVoZ3c/9MS3cBBfvk1DBsP7Ve9mmj1TfPlRjqBRjli8judvxGqLrz4GoLjpQgtrPEv+C/9m9mc+Na2QpI5PHL3pihJE38swyP0Y5i+nhIrvc4SJ5kw4NZb1Gb7WmGPJ8Kjm3piSD+MlvbdeV7pYBirZ2zUSumaup4ff1Wfo3yO4G2kofqdH+oqvsONDVZkOAtk/8herm1OSN1yS55zEKAUBi59zgclqGhmTT8Ij4UeG4/vUl9wkr1viU50UySsSKejV32QcUu8f3l+IFSoQolTGjIzORpaFU36QnZOx1FUdHIsNVJQI2AHT+ErvrxT/ld04xpQhxCqnLRZp7WUm/XhU0+WnZmRbr0kbienw2tW639yVuSsSis2QzTCZIt9XcJKmAiqpLRCntEfiUkXh60="

# Setup the build environment
install:
  # Install the requirements
  - pip install -r requirements.txt

script:
  # Build the website HTML
  - make

deploy:
  # Push the built HMTL to Github pages
  - provider: script
    script: doctr deploy . --built-docs _build --key-path .github_deploy_key.enc --deploy-repo ige-geophysics/ige-geophysics.github.io
    on:
      branch: master